# Generated by Django 5.0.3 on 2024-04-12 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='buyer',
            new_name='user',
        ),
    ]
